### ISSUE TITLE
isFid.test(filename) and isFT.test(filename)

### ISSUE THREAD

**Issue by andcastillo** [cheminfo/eln-plugin#2]
That property cannot be guessed  from the filename. Will need the metadata and look for FID or FT in the ##DATA TYPE. Do you agree? @lpatiny, @stropitek and @targos. None of the jcamp in Cali was named following the rules that you are checking currently.

**Comment by lpatiny** [comment]
Should we think about extending the jcamp converter to have a method like
'getKind' that returns a number. This number would correspond to static values like
TYPE_NMR_FID=1
TYPE_NMR_FT=2
TYPE_IR=3
TYPE_UV=4
TYPE_MS=5
...

**Comment by andcastillo** [comment]
2D_NMR and so on? I can make those changes if you agree. I need to run again the lims migration.

**Comment by lpatiny** [comment]
TYPE_NMR_2D_FT
But I don't think that this information should be stored in the database. I don't think you need to reimport the data. There is only ? FT spectra currently no ?

**Comment by andcastillo** [comment]
But we have jcamp, jcampFID or jcampFT depending on it. We don't store that info in the database but the place where we place the jcamp info is different. Now you use the isFid.test(filename) and isFT.test(filename) to choose it.

**Comment by andcastillo** [comment]
And not. There is FT and FID data.

**Comment by targos** [comment]
If there is a general and reliable way to know if it a an FT or FID
spectrum, please add the function in
https://github.com/cheminfo/nmr-metadata

2016-08-25 15:17 GMT+02:00 andres castillo notifications@github.com:
